config/routes.rb
Rails.application.routes.draw do
  resources :menu_planners
  get 'home/index'
  resources :dishes
  resources :ingredients, :except => [:new, :show]
  root 'home#index'
  get '/menu_planners/new/newweek', to: 'menu_planners#newweek'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_and_belongs_to_many :ingredients

  validates :dname, presence: true
  validates :dname, uniqueness:true
  validates :dname, uniqueness: { case_sensitive: false }
  paginates_per 10
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :dishes, dependent: :delete_all
  validates :iname, presence: true
  validates :iname, uniqueness:true
  validates :iname, uniqueness: { case_sensitive: false }

  paginates_per 7

end

app/models/menu_planner.rb
class MenuPlanner < ApplicationRecord
  belongs_to :dish
  has_many :ingredients, through: :dishes

  validates :date, presence: true
  validates :dish_type, uniqueness: { scope: :date,
    message: "already assigned for this day"}
  validates :dish, presence: true

  paginates_per 1


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, :with => :my_error

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all.page(params[:page])
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:dname, ingredient_ids: [])
    end

    def my_error
        redirect_to dishes_path, notice: "Dish with this ID not exist"
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, :with => :my_ing_error


  # GET /ingredients
  def index
    @ingredient = Ingredient.new
    all_ingredients
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    all_ingredients
      if @ingredient.save
        redirect_to ingredients_path, notice: 'Ingredient was successfully created.'
      else
       render :index
      end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
      if @ingredient.update(ingredient_params)
        redirect_to ingredients_path, notice: 'Ingredient was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
      redirect_to ingredients_path, notice: 'Ingredient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def all_ingredients
      @ingredients = Ingredient.all.page(params[:page])

    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:iname)
    end

    def my_ing_error
        redirect_to ingredients_path, notice: "Ingredient with this ID not exist"
    end
end

app/controllers/menu_planners_controller.rb
class MenuPlannersController < ApplicationController
  before_action :set_menu_planner, only: [:show, :edit, :update, :destroy]


  # GET /menu_planners
  # GET /menu_planners.json
  def index
    @menu_planners=MenuPlanner.all

    @this_week = Date.current.all_week  #returns a range (Mo...Sun) for the week of specific day
    @generated_week_menu = {}
    # for list of ingredients
    @week_ingredients = []
    #generated week to be added to array
    @menu_planners.each do |mp|
      if @this_week.include?(mp.date)
        @generated_week_menu=@generated_week_menu.deep_merge({mp.date=>{mp.dish_type=>[mp.dish,mp.id]}}) #to assign dish_type/dish to the date

        @week_ingredients << mp.dish.ingredients.collect(&:iname)#to collect ingredients from week dishes
        @week_ingredients.flatten!.uniq!
      end
    end    
  end

  # GET /menu_planners/1
  # GET /menu_planners/1.json
  def show
  end
  # GET /menu_planners/new
  def new
    @menu_planner = MenuPlanner.new
  end

  # GET /menu_planners/1/edit
  def edit
  end

  # POST /menu_planners
  # POST /menu_planners.json
  def create
    @menu_planner = MenuPlanner.new(menu_planner_params)
    respond_to do |format|
      if @menu_planner.save
        format.html { redirect_to @menu_planner, notice: 'Menu planner was successfully created.' }
        format.json { render :show, status: :created, location: @menu_planner }
      else
        format.html { render :new }
        format.json { render json: @menu_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_planners/1
  # PATCH/PUT /menu_planners/1.json
  def update
    respond_to do |format|
      if @menu_planner.update(menu_planner_params)
        format.html { redirect_to @menu_planner, notice: 'Menu planner was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_planner }
      else
        format.html { render :edit }
        format.json { render json: @menu_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_planners/1
  # DELETE /menu_planners/1.json
  def destroy
    @menu_planner.destroy
    respond_to do |format|
      format.html { redirect_to menu_planners_url, notice: 'Menu planner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_planner
      @menu_planner = MenuPlanner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_planner_params
      params.require(:menu_planner).permit(:date, :dish_type, :dish_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menu_planners_helper.rb
module MenuPlannersHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-inrow col-5">
    <%= form.label :dish_name %>
    <%= form.text_field :dname %>
  </div>

  <div class="field form-inrow col-5">
    <%= form.label(:ingredients, 'Select one or multiple ingredients (holding Ctrl/Command):') %>
    <%= collection_select(:dish, :ingredient_ids, Ingredient.all, :id, :iname, {}, {:class => 'form-control', :multiple => 'true'}) %>
  </div>


<br>
  <div class="actions">
  <%= form.submit "Save", class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>
<br>

<%= render 'form', dish: @dish %>
<br>
<%= link_to 'Show', @dish %> |
<%= link_to 'Back', :back %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Look how many dishes you can cook!</h3>
<div align="right"><a href="<%= new_dish_path %>" class="btn btn-primary" role="button">New dish</a></div><br/>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
    <th scope="col">Action</th>
  </tr>
</thead>
<tbody>
  <% @dishes.each do |dish| %>
  <tr>
    <td><%= link_to dish.dname, dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <% end %>
  </tr>
  </tbody>
</table>

<div align="right"><a href="<%= new_dish_path %>" class="btn btn-primary" role="button" >New dish</a></div><br/>


<div class = "container-flex pagination mt-2">
  <%= paginate @dishes %>
</div>

app/views/dishes/new.html.erb
<div ><h1>New Dish</h1></div>

<div>
  <%= render 'form', dish: @dish %> 
      <%= link_to 'Back', dishes_path %>
</div>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dish:</strong>
  <%= @dish.dname %>
</p>

<p><strong> Ingredients for this dish: </strong></p>
<p>
  <table>
      <tbody>
        <% @dish.ingredients.each do |di|%>
          <tr>
            <td><%= di.iname%></td>
            <td><%= link_to 'Delete', di, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
        <% end %>
    </tbody>
  </table>
</p>
<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', :back %> |
<%= link_to 'Delete dish', @dish, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back to Menu', menu_planners_path %>

app/views/home/index.html.erb
<html>
  <div class="container" style="height: 400px">
    <div class="row">
      <div class="col">
       <!-- image -->
       <img src="<%=image_path("welcome.png")%>" width="90%">
      </div>

      <div class="col"><h1 class="display-5 text-left">Welcome to Menu Planner</h1>
       <p class="lead text-center my-5" style="line-height: 40px">Menu planning gives you the opportunity to plan for week ahead and buy groceries accordingly. The question "What to cook for dinner?" will not bother you again. Also, you can reduce food waste and your food expences since you  are only buying what you you need for planned meals. </p>
       <div style= "text-align: center"><a class="btn btn-lg btn-info active" href="/menu_planners/" role="button">Plan your week!</a></div>
     </div>

    </div>

  </div>

</html>

app/views/ingredients/_form.html.erb
<%= form_with(model: @ingredient, local: true) do |form| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="input-group mb-5 col-5">
    <%= form.text_field :iname, class: 'form-control', placeholder: "Add new ingredient here..." %>
    <div class="input-group-btn ml-2"> <%= form.submit "Save", class: 'btn btn-primary'%></div>
  </div>

<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', :back %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "form", tag: @ingredient %>

<h3>Your ingredients: </h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.iname %></td>
          <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
          <td><%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?'} %>

            </td>
        </tr>
     <% end %>

  </tbody>
</table>

<div class = "container-flex pagination mt-2">
  <%= paginate @ingredients %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- to make flexible screen -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Menu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url('<%=image_path("food2.png")%>');  background-size: 300px; ">
    <!-- navbar -->
    <header>
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #98DAE2">
        <div class="container">

        <h1 class="navbar-brand order-1"><img src="<%=image_path("menuplannerlogo.png")%>" height="30"></h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/home/index"> Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="<%=menu_planners_path%>">Menu</a>
            <a class="nav-item nav-link" href="/menu_planners/new">Plan your day</a>
            <a class="nav-item nav-link" href="<%=dishes_path%>">Dishes</a>
            <a class="nav-item nav-link" href="<%=ingredients_path%>">Ingredients</a>
          </div>
        </div>
            </nav>
    </header>
    <!-- /navbar -->
    <div class="container yield" style="margin-top:100px; w-50;">
      <%= yield %>
    </div>

  </body>

</html>

app/views/menu_planners/_form.html.erb
<%= form_with(model: menu_planner, local: true) do |form| %>
  <% if menu_planner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_planner.errors.count, "error") %> prohibited this menu_planner from being saved:</h2>

      <ul>
      <% menu_planner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">


    <%= form.label :date %>
      <% if params.has_key?(:date)%> <!-- for preselecting date for NO DISH Assigned else->new -->
        <%= form.date_select :date, start_year: 2020, default: params['date'].to_date %>
          <% else %>
            <%= form.date_select :date, start_year: 2020%>
          <% end %>
  </div>

  <div class="field">
      <% for i  in 1..3 do %>
        <% if params.has_key?(:dtype) %> <!--for dish-type radio buttons-->
          <% if params['dtype'].to_i==i %>
            <%= radio_button("menu_planner","dish_type", i, {checked:true}) %>
              <% else %>
              <%= radio_button("menu_planner","dish_type", i) %>
                <% end %>
            <% else %>
              <%= radio_button("menu_planner","dish_type", i) %>
                <% end %>
        <% if i==1 %>
        Breakfast
          <% elsif i==2 %>
            Lunch
             <% elsif i==3 %>
              Dinner
                <% end %>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :dish_id %>
    <%= form.collection_select :dish_id, Dish.all, :id, :dname, include_blank: true %>
  </div>

  <h6> Choose ingredient from the list or add <%=link_to "New Dish", new_dish_path %></h6><br>


  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/menu_planners/edit.html.erb
<h1>Editing Menu Planner</h1>

<%= render 'form', menu_planner: @menu_planner %>

<%= link_to 'Show', @menu_planner %> |
<%= link_to 'Back', menu_planners_path %>

app/views/menu_planners/index.html.erb
<% if defined?notice %>
<p id="notice"><%= notice %></p>
<% end %>
<h2 class="text-center">Menu for this week</h1>
<p align="right"><a href="javascript:window.print();">Print</a></p>
<table class="table table-bordered my-5" style="height:400px">
  <!-- < %# <№%=@generated_week_menu.inspect%> %> -->
  <tbody>
    <% for i  in 0..3 do %>
    <tr>
          <% if i==0 %>
            <th scope="row">Type / Date</th>
          <% elsif i==1 %>
            <th scope="row">Breakfast</th>
          <% elsif i==2 %>
            <th scope="row">Lunch</th>
          <% elsif i==3 %>
            <th scope="row">Dinner</th>
          <% end %>
     <% @this_week.each do |twday| %>
          <% if i==0 %>
            <th scope="row" ><%= twday.strftime("%b %d %n %A") %></th>
          <% else %>
            <td scope="row" style="width:125px;">
              <% if @generated_week_menu.key?(twday) %>
                  <% if @generated_week_menu[twday].key?(i) %>
                     <%= link_to @generated_week_menu[twday][i][0].dname, @generated_week_menu[twday][i][0] %>&nbsp;
                     <a href= "<%=edit_menu_planner_path(:id=>@generated_week_menu[twday][i][1])%>">&#9998;</a>
                  <% else %>
                    <%= link_to 'Add Dish', new_menu_planner_path(:date=>twday,:dtype=>i)%>
                  <% end %>
              <% else %>
                 <%= link_to 'Add Dish', new_menu_planner_path(:date=>twday)%>
              <% end %>
            </td>
          <% end %>
    <% end %>
      </tr>
   <% end %>
  </tbody>
</table>
<p>
<b>Ingredients for this week</b>
<ul style="list-style-type:none;">
<% @week_ingredients.each do |wi| %>
<li> &#x2610;&nbsp <%=wi%></li>
<% end %>
</ul>
</p>
<!-- <div class = "container-flex pagination mt-2">
  <#%= paginate @menu_planners %>
</div> -->
<!-- <a class="btn btn-primary btn-lg" href="/menu_planners/new/newweek" role="button">Generate menu</a> -->

app/views/menu_planners/new.html.erb
<div style="height: 400px">
  <h1 class="text-center my-4">Day menu</h1>
<br>

<%= render 'form', menu_planner: @menu_planner %>

<%= link_to 'Back', menu_planners_path %>
</div>

app/views/menu_planners/newweek.html.erb
<h1> New week is generated</h1>
<% @dishes.each do |d| %>
<%= d.dname %> <br>
<% end %>
<hr/>
<%= @menuitem %>
<hr/>
<%= link_to 'Back', menu_planners_path %>

app/views/menu_planners/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Date:</strong>
  <%= @menu_planner.date %>
</p>

<p>
  <strong>Dish type:</strong>
    <% if @menu_planner.dish_type== 1 %>
      Breakfast
        <% elsif @menu_planner.dish_type== 2 %>
          Lunch
            <% else @menu_planner.dish_type== 3 %>
              Dinner
      <% end %>
</p>

<p>
  <strong>Dish:</strong>
  <%= link_to @menu_planner.dish.dname, dish_path(@menu_planner.dish) %>
</p>

<%= link_to 'Edit', edit_menu_planner_path(@menu_planner) %> |
<%= link_to 'Back', menu_planners_path %>